language: elixir

otp_release:
  - 22.2
  - 23.1
elixir:
  - 1.10.4
  - 1.11.0

env:
  - ES_TARBALL='ubuntu/EventStore-OSS-Linux-Ubuntu-18.04-v5.0.8.tar.gz' ES_VERSION=4

script:
  - "mix do deps.get, format --check-formatted, compile --force --warnings-as-errors, test --cover"

before_install:
  - wget https://eventstore.org/downloads/${ES_TARBALL}
  - tar xf EventStore*.tar.gz
  - cd EventStore* && ./run-node.sh --run-projections=all --start-standard-projections=true --mem-db 2>&1> eventstore.log &

after_success:
  - mix inch.report
  - head -n 7 EventStore*/eventstore.log

after_failure:
  - cat EventStore*/eventstore.log

after_script:
  - killall -SIGINT clusternode
