language: elixir

otp_release:
  - 21.0
elixir:
  - 1.7.3

env:
  - EVENT_STORE_VERSION='14.04-v4.1.1-hotfix1' ES_VERSION=4

script:
  - "mix do format --check-formatted, deps.get, test --cover"

before_install:
  - wget https://eventstore.org/downloads/EventStore-OSS-Ubuntu-${EVENT_STORE_VERSION}.tar.gz
  - tar xf EventStore*.tar.gz
  - cd EventStore* && ./run-node.sh --run-projections=all --start-standard-projections=true --mem-db 2>&1> eventstore.log &

after_success:
  - mix inch.report
  - head -n 7 EventStore*/eventstore.log

after_failure:
  - cat EventStore*/eventstore.log

after_script:
  - killall -SIGINT clusternode
